
return {
  ['ddu-ff'] = function ()
    _G.TKC.utils.nvim.buffer_keymap('n', '<CR>', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { params = { command = 'tabedit' } })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'i', function ()
      vim.fn['ddu#ui#do_action']('openFilterWindow')
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'dl', function ()
      -- TODO mr delete ..
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'delete' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'q', function ()
      vim.fn['ddu#ui#do_action']('quit')
    end)
  end
  , ['ddu-ff-filter'] = function ()
    _G.TKC.utils.nvim.buffer_keymap('i', '<CR>', '<Esc><Cmd>close<CR>')
    _G.TKC.utils.nvim.buffer_keymap('n', '<CR>', '<Cmd>close<CR>')
  end
  , ['ddu-filer'] = function ()
    _G.TKC.utils.nvim.buffer_keymap('n', '<CR>', function ()
      vim.fn.clearmatches()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'open', params = { command = 'tabedit' } })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'yy', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'copy' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'p', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'paste' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'rr', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'rename' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'mm', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'move' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'dl', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'delete' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'N', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'newFile' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'D', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'newDirectory' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', '.', function ()
      vim.fn['ddu#ui##do_action']('createMyRoot')
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'l', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'narrow' })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'h', function ()
      vim.fn['ddu#ui#do_action']('itemAction', { name = 'narrow', params = { path = '..' } })
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'q', function ()
      vim.fn.clearmatches()
      vim.fn['ddu#ui#do_action']('quit')
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 't', function ()
      vim.fn['ddu#ui#do_action']('terminalOpen')
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'e', function ()
      vim.fn['ddu#ui#do_action']('explorerOpen')
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', 'c', function ()
      vim.fn['ddu#ui#do_action']('dduFilerDiff')
    end)
    _G.TKC.utils.nvim.buffer_keymap('n', '<F4>', function ()
      vim.fn['ddu#redraw'](vim.b['ddu_ui_name'], {refreshItems = 1})
    end)
  end
}
