nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> <ESC><ESC> denite#do_map('quit')
nnoremap <silent><buffer><expr> <C-t> denite#do_map('do_action', 'right_tabopen')
nnoremap <silent><buffer><expr> <C-w> denite#do_map('do_action', 'denite_side_by_side')
nnoremap <silent><buffer><expr> n denite#do_map('toggle_select')
nnoremap <silent><buffer><expr> aa denite#do_map('toggle_select_all')
nnoremap <silent><buffer><expr> dd denite#do_map('do_action', 'delete')
"nnoremap <silent><buffer><expr> ' denite#do_map('quick_move')
