[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#auto_recache = 1
'''

# ==========================================================
# base
# ==========================================================
[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_patterns = ['.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.myRoot']
'''
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'lambdalisue/mr.vim'
hook_add = '''
luafile ~/.config/nvim/plugins/mr.lua
'''

# ==========================================================
# looks
# ==========================================================
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
luafile ~/.config/nvim/plugins/molokai.lua
'''
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
luafile ~/.config/nvim/plugins/lualine.lua
'''

# ==========================================================
# git
# ==========================================================
[[plugins]]
repo = 'lambdalisue/gin.vim'
hook_add = '''
luafile ~/.config/nvim/plugins/gin.lua
'''
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
nnoremap <silent> > :GitGutterNextHunk<CR>zz
nnoremap <silent> < :GitGutterPrevHunk<CR>zz
'''

# ==========================================================
# ddu
# ==========================================================
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim', 'pum.vim']
hook_add = '''
luafile ~/.config/nvim/plugins/ddu.lua
'''
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'
[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'
[[plugins]]
repo = 'kuuote/ddu-source-mr'
on_source = 'ddu.vim'
[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'
on_source = 'ddu.vim'


# ==========================================================
# markdown
# ==========================================================
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
luafile ~/.config/nvim/plugins/memolist.lua
'''
[[plugins]]
repo = 'mattn/vim-maketable'
hook_add = '''
luafile ~/.config/nvim/plugins/vim-maketable.lua
'''

# ==========================================================
# lsp
# ==========================================================
[[plugins]]
repo = 'neovim/nvim-lspconfig'
[[plugins]]
repo = 'williamboman/mason.nvim'
[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = '''
luafile ~/.config/nvim/plugins/mason-lspconfig.lua
'''

# ==========================================================
# ddc
# ==========================================================
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_add = '''
luafile ~/.config/nvim/plugins/ddc.lua
'''
[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc.vim'
[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_add = '''
call popup_preview#enable()
'''
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
hook_add = '''
autocmd User PumCompleteDone call vsnip_integ#on_complete_done(g:pum#completed_item)
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'
[[plugins]]
repo = 'octaltree/cmp-look'
on_source = 'ddc.vim'

# ==========================================================
# syntax
# ==========================================================
[[plugins]]
repo = 'leafgarland/typescript-vim'
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_new_list_item_indent = 2
'''
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
