[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
source ~/.config/nvim/plugins/molokai.rc.vim
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.config/nvim/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
hook_add = '''
nnoremap <silent> <Space>p :<C-u>MarkdownPreview<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_patterns = ['.myroot', '.myroot/', '.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[plugins.ftplugin]
defx = '''
source ~/.config/nvim/plugins/defx_buffer_map.rc.vim
'''

# ==========================================================
# denite
# ==========================================================

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[plugins.ftplugin]
denite = '''
source ~/.config/nvim/plugins/denite_buffer_map.rc.vim
'''

[[plugins]]
repo = 'takashi1coq/denite-mymarks'

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'ujihisa/neco-look'

# ==========================================================
# LanguageClient-neovim
# ==========================================================

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''

# ==========================================================
# git
# ==========================================================

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
nnoremap <silent> > :GitGutterNextHunk<CR>zz
nnoremap <silent> < :GitGutterPrevHunk<CR>zz
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
source ~/.config/nvim/plugins/gina.rc.vim
'''

