[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# gkjgh/cobalt
# tomasr/molokai
# ==========================================================

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
source ~/.config/nvim/plugins/gruvbox.rc.vim
'''

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python_host_prog = 'usr/lib/python2.7'
let g:python3_host_prog = '/usr/lib/python3.6'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.config/nvim/plugins/memolist.rc.vim
'''
