[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# morhetz/gruvbox
# shawncplus/skittles_berry
# tomasr/molokai
# ==========================================================

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
source ~/.config/nvim/plugins/molokai.rc.vim
let loaded_matchparen = 1
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.config/nvim/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
au BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'firefox'
let g:previm_disable_default_css = 1
let g:previm_custom_css_path = '~/.config/nvim/plugins/previm_custom.css'
nnoremap <silent> <Space>p :<C-u>PrevimOpen<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
nnoremap <silent> <Space>f
\ :<C-u>Defx -listed -resume -buffer-name=tab`tabpagenr()`<CR>
'''

[plugins.ftplugin]
defx = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

# ==========================================================
# denite
# ==========================================================

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_source = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''
hook_add = '''
source ~/.config/nvim/plugins/denite_keymap.rc.vim
'''

[[plugins]]
repo = 'neoclide/denite-git'

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python_host_prog = ''
let g:python3_host_prog = system('which python3 | tr -d "\n"')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
source ~/.config/nvim/plugins/deoplete.rc.vim
'''
