[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# morhetz/gruvbox
# shawncplus/skittles_berry
# ==========================================================

[[plugins]]
repo = 'shawncplus/skittles_berry'
hook_add = '''
source ~/.config/nvim/plugins/skittles_berry.rc.vim
'''

# ==========================================================
# deoplete
# ==========================================================

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python_host_prog = '/usr/lib/python2.7'
let g:python3_host_prog = '/usr/lib/python3.6'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.config/nvim/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
let g:previm_open_cmd = 'chromium'
nnoremap <silent> <Space>p :<C-u>PrevimOpen<CR>
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''
