[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
source ~/.config/nvim/plugins/molokai.rc.vim
'''

# ==========================================================
# syntax
# ==========================================================

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
source ~/.config/nvim/plugins/memolist.rc.vim
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'cd app & yarn install'
hook_add = '''
nnoremap <silent> <Space>p :<C-u>MarkdownPreview<CR>
let g:mkdp_auto_close = 0
'''

[[plugins]]
repo = 'mattn/vim-maketable'
hook_add = '''
vnoremap t :'<,'>MakeTable!<CR>
nnoremap c :UnmakeTable<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_patterns = ['.myroot', '.myroot/', '.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[plugins.ftplugin]
defx = '''
source ~/.config/nvim/plugins/defx_buffer_map.rc.vim
'''

# ==========================================================
# denite
# ==========================================================

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[plugins.ftplugin]
denite = '''
source ~/.config/nvim/plugins/denite_buffer_map.rc.vim
'''

[[plugins]]
repo = 'takashi1coq/denite-mymarks'

# ==========================================================
# COC - LSP client
# ==========================================================

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

# ==========================================================
# git
# ==========================================================

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
nnoremap <silent> > :GitGutterNextHunk<CR>zz
nnoremap <silent> < :GitGutterPrevHunk<CR>zz
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
source ~/.config/nvim/plugins/gina.rc.vim
'''

